name: TreeFall
version: 1.4.0
main: me.dagxam.treefall.TreeFallPlugin
api-version: 1.21
author: Dagxam
description: Breaks an entire tree (logs + leaves) safely with limits and config.

permissions:
  treefall.use:
    description: Allows using TreeFall when breaking logs.
    default: true
